name: sessionful
description: Dart package which allow to multiplex communication in separate channels over any transport.
version: 1.0.0
repository: https://github.com/TheTosters/sessionful

environment:
  sdk: ^3.2.6

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
